version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_db"
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    ports:
      - "3000:8000"
    depends_on:
      - db
    links:
      - db